sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: X8bNCNmCnPJ/K2dMfo0ihrOODw86Jw7J2Xoz09FmzSiKUsViHLR2RybLwTrRBf9W0L/vsW0A9IpK+NwVlJFlu7ud91jmeujeh7itfNm6XApvpxbLPvHL+kJqwAU0Vv1C0CAF/RBtueUTGnzOyJNQV9hKR43Y/eOs5XqBDOfMFwkxQ65oKqzql2/qnCQLanXIexQ9ueV4b6XmUZSjPuztvK3PZ8zRchpRaZYNvUw65X8zs4FUpOZC0Rb3bAcThfBwaCcRTOi+M3DYu2o82v95i9YCWP0G+lHVM3ZDuy65cL2kmTbG4H1mP564vqOftO2ugf95WcSraEl9dfPD9HnS4clrQuaUmtDrpoRiO2XvL/nOne1rnOPYK/9SHV55luSExrUfHgRKkS7CQze1Pr9E0r+N96LIF1uWGnpBisUY5ARKm5SIVCA/egUsZSOUf9Kp2KM7nedEy7jjVFaWxFepeXUtXTe1WqDi5M6eWRkMXpu/LCL9GU8GpRs3xDqhVuHNC72LwFvz0Aqvw5HaDBXH1tRlv7tNHPzhlPcUMnaL/DmrrYfCG1zOolVxavmS/hxKJoUFBNp/6SdIli+HQwQc4GqUJf3Tg2kuRbLhMms3q5ohoKA2uihm8S/c1l7ACBKFgxkeIZffgNEiAHolUL3RC9rqT6iewfalW68JY0PLS7o=
branches:
  only:
  - master
  - gh-pages
