sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: EhNt0uHsBsMQiyAE50YjaGqIYLc+/0eJ0RWlN4o6nivGOTc4VYzGp4MEHZDhVMDdZcCL9hgh/XMD8KuBM39EJ5Y9/JKR5Y40t0B4bZPRyT5uvvuP+KgF4SoVe+niJDv3q5wFi3FVRpxrUUlL9mwnGGa0pDEZwasJp5Z4eJ5vquFLD5HtH0RVsdCZcg41328IgISTacbgJXEdiZWz1ZykkDTVsNR5c8f3926PS2cDobA5VXKthw6VL0u6CXXzed16pvTZCh4pwZ3oa5CmXw9bRkgr+nOqFH9/pI/dbNIY3EHVBM20z4r80DNBGmjbXee2k4EkNSk75HPrW3TpSX1VDceYwKLwu1WU2IOGQkN+2xL35GDWLGAktSR0EirLlRo3pOKlOp8SInAOpKIpyyk5QjPRME5jPGSzx8wDZND2+CDnXlZAiQY1CtDSC+8CJV0p8tBVKBwlTCmSEBNtsIDmmL52CJ8Z/IMB6Z4ZLckLjS+h5Qu67Vj4aqLxtdgPkZKobp3vRg/D3jJpwfbmZ2iwZCzpDM5V9USfpvUuLPcTnDk2cnrQtjtsouA2Q1a9Mpjlbxx55MCaRZUYNdJiOAi/fh6ooD0nhU6DzY5qeQ3jzwMaZxNspT83wZFMcIWMz5y2DIyGE4QbYfjsbYcmGw6DrbzxnjDxW5UYsfPMzx3zLls=
branches:
  only:
  - master
  - gh-pages
