sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: FYZN09gieXXAhDybQYGeUSnws4gTt4cGxcdOm+ode4CZuPZbcZmpUKyYge9WQ6fucjSiYxodjLV1AUmDK35l0P5EtXE2WVy55YOjKsff73DDld9gktgUB+h0+yL4LpVSHaJIo5aBXW6afgiYfNHEJG51t3GefBisL2TGcSDjFH1z8NrWswslazjSm4gBCWSaPZjlQLHvQIoWL4bQ76ydtwh3UsCSZCXNgnXNFZhKQZhDI7oy1grNpm7jAkfHXIxGlHSUmJRblCRooLtRNFYi1IRNVGj3LMHh/YKVCJgzzI7lruti+0i4hRVvcLNRLFRrb0f8NiLWJZ46xlj28eBO866zhDD8rjpqnTOZhN5jFnEjvqRcQMwUffBQXjwVjJw8hAbEbcxAx9Mizy09w27COeffHvYUJdgPDrYHoNLRtKV/waLI/+Ij71RWRv2IVoTIf744lcvxd4dVoZS7/IYO6dXnHHpoOqI5oAes4nQ/nbJMur8mjchKicTuStqcl8EWcavT6s1Sf41Ni6ren1wqceecPPwQTrVBsHjJcLVz8fuZ/cj/SLKXIpevCWbOlinRVGfULjeEON9EFZyAwZbmuxy7mzJpM2suibVLsvSm55JrgH36fheg8rUEi3E9bSzbQHBEfwngXs2K36VcHc7CD+bQPJzpyeBOEgEtnNlRUJk=
branches:
  only:
  - master
  - gh-pages
